site_name: pg-mgt-utils
site_url: https://stevek-skzone.github.io/pg-mgt-utils
repo_url: https://github.com/stevek-skzone/pg-mgt-utils
repo_name: stevek-skzone/pg-mgt-utils
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
  - meta
watch:
  - pg_mgt_utils
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/waynerv/cookiecutter-pypackage
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/waynerv/cookiecutter-pypackage
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/stevek-skzone/pg-mgt-utils
      name: Github
    - icon: material/email
      link: "mailto:dev@skzone.org"
